[workspace]
members = [ "russh-keys", "russh", "russh-libsodium", "russh-config", "cryptovec"]

[patch.crates-io]
russh = { path = "russh" }
russh-keys = { path = "russh-keys" }
russh-libsodium = { path = "russh-libsodium" }
russh-cryptovec = { path = "cryptovec" }
russh-config = { path = "russh-config" }
